import cantarito1PNG from "@LevelClayCraft/assets/cantarito-1.png";
import cantarito2PNG from "@LevelClayCraft/assets/cantarito-2.png";
import cantarito3PNG from "@LevelClayCraft/assets/cantarito-3.png";
import cantarito4PNG from "@LevelClayCraft/assets/cantarito-4.png";
import olla1PNG from "@LevelClayCraft/assets/olla-1.png";
import olla2PNG from "@LevelClayCraft/assets/olla-2.png";
import olla3PNG from "@LevelClayCraft/assets/olla-3.png";
import olla4PNG from "@LevelClayCraft/assets/olla-4.png";
import olla5PNG from "@LevelClayCraft/assets/olla-5.png";
import olla6PNG from "@LevelClayCraft/assets/olla-6.png";
import plato1PNG from "@LevelClayCraft/assets/plato-1.png";
import plato2PNG from "@LevelClayCraft/assets/plato-2.png";
import plato3PNG from "@LevelClayCraft/assets/plato-3.png";
import plato4PNG from "@LevelClayCraft/assets/plato-4.png";

export const cantarito1 = cantarito1PNG;
export const cantarito2 = cantarito2PNG;
export const cantarito3 = cantarito3PNG;
export const cantarito4 = cantarito4PNG;
export const olla1 = olla1PNG;
export const olla2 = olla2PNG;
export const olla3 = olla3PNG;
export const olla4 = olla4PNG;
export const olla5 = olla5PNG;
export const olla6 = olla6PNG;
export const plato1 = plato1PNG;
export const plato2 = plato2PNG;
export const plato3 = plato3PNG;
export const plato4 = plato4PNG;

export * from "@LevelClayCraft/components/cantarito/Cantarito";
export * from "@LevelClayCraft/components/cantarito/CantaritoContainer";
export * from "@LevelClayCraft/components/cantarito/CantaritoRack";
export * from "@LevelClayCraft/components/cantarito/SortableCantarito";
export * from "@LevelClayCraft/components/olla/Olla";
export * from "@LevelClayCraft/components/olla/OllaContainer";
export * from "@LevelClayCraft/components/olla/OllaRack";
export * from "@LevelClayCraft/components/olla/SortableOlla";
export * from "@LevelClayCraft/components/plato/Plato";
export * from "@LevelClayCraft/components/plato/PlatoContainer";
export * from "@LevelClayCraft/components/plato/PlatoRack";
export * from "@LevelClayCraft/components/plato/SortablePlatos";
export * from "@LevelClayCraft/mocks";
export * from "@LevelClayCraft/win-conditions";
export * from "@LevelClayCraft/LevelClayCraft";
export * from "@LevelClayCraft/useLevelClayCraft";
