import borrachitoPNG from "@LevelCandy/assets/borrachito.png";
import cocadaPNG from "@LevelCandy/assets/cocada.png";
import jamoncilloPNG from "@LevelCandy/assets/jamoncillo.png";
import mazapanPNG from "@LevelCandy/assets/mazapan.png";
import obleasPNG from "@LevelCandy/assets/obleas.png";
import paleta1PNG from "@LevelCandy/assets/paleta1.png";
import paleta2PNG from "@LevelCandy/assets/paleta2.png";
import paleta3PNG from "@LevelCandy/assets/paleta3.png";
import paleta4PNG from "@LevelCandy/assets/paleta4.png";
import pipitoriaPNG from "@LevelCandy/assets/pipitoria.png";

export const borrachito = borrachitoPNG;
export const cocada = cocadaPNG;
export const jamoncillo = jamoncilloPNG;
export const mazapan = mazapanPNG;
export const obleas = obleasPNG;
export const paleta1 = paleta1PNG;
export const paleta2 = paleta2PNG;
export const paleta3 = paleta3PNG;
export const paleta4 = paleta4PNG;
export const pipitoria = pipitoriaPNG;

export * from "@LevelCandy/components/BoxDroppable";
export * from "@LevelCandy/components/Candy";
export * from "@LevelCandy/components/EmptySpaceDroppable";
export * from "@LevelCandy/mocks";
export * from "@LevelCandy/win-conditions";
export * from "@LevelCandy/models/ICandy";
export * from "@LevelCandy/LevelCandy";
export * from "@LevelCandy/useLevelCandy";
